### ISSUE TITLE
disable @semantic-release/github plugin

### ISSUE THREAD

**Issue by missinglink** [pelias/ci-tools#10]
at some point `semantic-release` changed their defaults from just publishing to `npm` to publishing to `npm` and also `github` 🤷‍♂️ 

so despite us not touching the config in forever, some builds are now showing as failed, such as this one:
https://github.com/geocodeearth/ge/runs/6624531474?check_suite_focus=true

worth noting it's not terrible since the `npm` publish step comes first and still succeeds:
`[11:14:55 AM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/npm"`

but after that comes the `github` plugin which fails and the whole build displays a nasty red X
`[11:15:05 AM] [semantic-release] › ✖  Failed step "publish" of plugin "@semantic-release/github"`

this comment suggests a fix:
https://github.com/semantic-release/semantic-release/issues/922#issuecomment-418890603

but also links to a PR where the team seem to have addressed the configurability of plugins in:
https://github.com/semantic-release/semantic-release/pull/936

this issue is to try and figure out a way to run the `npm` publish step but not the `github` step

**Comment by orangejulius** [comment]
As far as I know semantic release has always published to GitHub and we _do_ actually want that. It lets us automatically turn our commit messages into release notes (for example [here](https://github.com/pelias/api/releases/tag/v5.53.0).

My guess is the issue you're seeing is because we're piggybacking a Geocode Earth package on top of the Pelias CI tools. It's a shortcut that will _probably_ work, but may have issues. I think this is something we want to fix in the https://github.com/geocodeearth/ge repository directly.

Looking back, the `master` branch builds for that repo have been failing almost since day 1.

**Comment by missinglink** [comment]
Agh ok that makes more sense, I thought it was odd that they would have changed the default behaviour 😆
